name: Publish docker image

on:
  push:
    branches:
      - master
      - main
      - "*/build/docker/*"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # We don't need any keys, but the docker action expects an SSH agent to be
    # up, and the action requires at least one private key. Once we migrate to
    # using artifacts for internal dependencies, we can remove this.
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: |
          ${{ secrets.MLUTILS_DEPLOY_KEY }}
    - uses: docker/setup-buildx-action@v2

    - uses: ./.github/actions/publish-docker
      with:
        repository: 455661021047.dkr.ecr.eu-central-1.amazonaws.com/python-ci

    - uses: ./.github/actions/publish-docker
      with:
        repository: 455661021047.dkr.ecr.eu-central-1.amazonaws.com/python-ci
        target: test
