name: Python Lint

on: [workflow_call, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: psf/black@22.1.0
        with:
          src: "."
      - uses: isort/isort-action@master
        with:
          sortPaths: "."
          isortVersion: "5.10.1"
      - name: Run flake8
        run: |
          pip install flake8 flake8-simplify flake8-comprehensions flake8-bugbear darglint flake8-pep585
          python -m flake8 .
