name: Python Lint

on: 
  workflow_call:
    inputs:
      flake8_plugins:
        type: string
        description: space-delimited list of flake8 plugins to install
        required: false
      path:
        type: string
        description: Path of package, relative to the repo root
        required: false
        default: '.'

jobs:
  python-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: psf/black@22.1.0
        with:
          src: ./${{ inputs.path }}
      - uses: isort/isort-action@master
        with:
          sortPaths: ./${{ inputs.path }}
          isortVersion: "5.10.1"
      - name: Run flake8
        working-directory: ./${{ inputs.path }}
        run: |
          pip install flake8 ${{ inputs.flake8_plugins }}
          python -m flake8 .
