name: Python Type Checking

on: [workflow_call, pull_request]

jobs:
  python-mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version:
          - "3.9"

    defaults:
      run:
        # Necessary for the mamba-org/provision-with-micromamba action
        shell: bash --login -eo pipefail {0}

    env:
      LD_LIBRARY_PATH: /home/runner/micromamba/envs/bindgen/lib:$LD_LIBRARY_PATH
      PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

    # I don't love having all this workflow setup stuff inline in this file
    # but the other options are:
    # - make them their own .yml: they can't be used as steps within a job, only as entire jobs
    # - make them an action: they can't do variable interpolation so you have to pass
    # everything in as a parameter (laborious)
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Setup SSH keys to clone private repos
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.MLUTILS_DEPLOY_KEY }}

      # Configure conda
      - name: Set up micromamba
        uses: mamba-org/provision-with-micromamba@5fe88d370c741fc3567126d17c5af0b9620bd60d
        with:
          cache-downloads: true
          cache-downloads-key: "mamba-${{ hashFiles('environment.lock') }}"
          # to generate environment.lock run, see docker/update-reqs.sh
          environment-file: environment.lock
          environment-name: bindgen

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: "~/.cache/pip"
          key: "pip-${{ hashFiles('requirements-test.txt') }}"
          restore-keys: |
            pip-${{ hashFiles('requirements-test.txt') }}
            pip-

      - name: Install package
        run: |
          python -m pip install --no-deps -r requirements-test.txt

      - name: Mypy
        run: |
          python -m mypy
