# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
    - name: Log into AWS CodeArtifact
      run: | 
        aws codeartifact login --tool twine --repository charm-pypi --domain charm-pypi \
        --domain-owner 455661021047 --region eu-west-1
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository-url $REPO_URL dist/*
