# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MLUTILS_DEPLOY_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade twine build

    - name: Log into AWS CodeArtifact
      run: | 
        aws codeartifact login --tool twine --repository charm-pypi --domain charm-pypi \
        --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region eu-west-1

    - name: Build
      run: python -m build

# We only run a publish if this CI is running after a tag/release.
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: twine upload --repository codeartifact dist/*
