name: Python 3.9 Test

on: [workflow_call, pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/pytest
        with:
          python_version: '3.9'
