name: Unit Testing

on:
  pull_request: {}
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MLUTILS_DEPLOY_KEY:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    # Configure conda
    - name: Set up micromamba
      uses: mamba-org/provision-with-micromamba@5fe88d370c741fc3567126d17c5af0b9620bd60d
      with:
        cache-downloads: true
        cache-downloads-key: "mamba-${{ hashFiles('environment.lock') }}"
        # to generate environment.lock run, see docker/update-reqs.sh
        environment-file: environment.lock
        environment-name: unit-testing
        extra-specs:
          python=3.9

    - name: Cache pip downloads
      uses: actions/cache@v3
      with:
        path: "~/.cache/pip"
        key: "pip-${{ hashFiles('setup.cfg') }}"
        restore-keys: |
          pip-${{ hashFiles('setup.cfg') }}
          pip-

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Log in to AWS CodeArtifact
      run: |
        aws codeartifact login --tool pip --repository charm-pypi --domain charm-pypi \
        --domain-owner 455661021047 --region eu-west-1

    - name: Install package
      run: |
        python -m pip install .[tests]

    - name: Test with pytest
      run: |
        python -m pytest --cov-report=xml

    - name: Code Coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '80 100'
